# Generated by Django 3.2.15 on 2023-02-20 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cim_users', '0002_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='diagnosis',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='patient_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cim_users.patient'),
        ),
    ]
