# Generated by Django 3.2.15 on 2023-02-20 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cim_users', '0004_auto_20230220_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='doctor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cim_users.team'),
        ),
    ]
